// <auto-generated />
using System;
using Alumnado.BD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alumnado.BD.Migrations
{
    [DbContext(typeof(pepe))]
    [Migration("20220612232755_Inscripto")]
    partial class Inscripto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Alumnado.BD.Data.Entidades.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GradoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreAlumno")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NotaAlumno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GradoId");

                    b.HasIndex(new[] { "DNI" }, "AlumnoDNI_UQ")
                        .IsUnique();

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("Alumnado.BD.Data.Entidades.Grado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CodigoGrado")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreMateria")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CodigoGrado" }, "GradoCodigo_UQ")
                        .IsUnique();

                    b.ToTable("Grados");
                });

            modelBuilder.Entity("Alumnado.BD.Data.Entidades.Inscripto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoAlumnoMatriculado")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("GradoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId")
                        .IsUnique();

                    b.HasIndex("GradoId");

                    b.HasIndex(new[] { "AlumnoId", "GradoId" }, "AlumnoGradoId_UQ")
                        .IsUnique();

                    b.ToTable("Inscriptos");
                });

            modelBuilder.Entity("Alumnado.BD.Data.Entidades.Alumno", b =>
                {
                    b.HasOne("Alumnado.BD.Data.Entidades.Grado", "Grado")
                        .WithMany("Alumnos")
                        .HasForeignKey("GradoId");

                    b.Navigation("Grado");
                });

            modelBuilder.Entity("Alumnado.BD.Data.Entidades.Inscripto", b =>
                {
                    b.HasOne("Alumnado.BD.Data.Entidades.Alumno", "Alumno")
                        .WithOne("Inscripto")
                        .HasForeignKey("Alumnado.BD.Data.Entidades.Inscripto", "AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alumnado.BD.Data.Entidades.Grado", "Grado")
                        .WithMany("Inscriptos")
                        .HasForeignKey("GradoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Grado");
                });

            modelBuilder.Entity("Alumnado.BD.Data.Entidades.Alumno", b =>
                {
                    b.Navigation("Inscripto");
                });

            modelBuilder.Entity("Alumnado.BD.Data.Entidades.Grado", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Inscriptos");
                });
#pragma warning restore 612, 618
        }
    }
}
